name: End-to-end tests
on: [push]
jobs:

  murilo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        start: npm start
    - name: Install modules
      run: npm install
    - name: Ionic Cordova
      run: ionic cordova run browser -l

  cypress-run-1:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          command: npm run cypress:test1
  cypress-run-2:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          command: npm run cypress:test2
  cypress-run-3:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          command: npm run cypress:test3